export const opportunities = [
  {
    id: "opp-001", rank: 1, decision: "VERIFY_FIRST", decisionLabel: "补证后追", decisionTone: "warning", risk: "中风险",
    buyerName: "Aurora Beverage Labs", country: "美国", city: "California", industry: "功能饮品",
    score: 94, truth: 88, window: "窗口打开", access: "补充条件", accessTone: "warning", published: "7 天前",
    demand: "有机饮料级抹茶粉", quantity: "500 kg / 首批",
    whyNow: "7 天前发布新 RFQ；官网同步上线抹茶能量饮新品，采购岗位本周更新。",
    whyNowReasons: ["新 RFQ 发布仅 7 天", "新品页同步上线", "采购岗位正在扩充"],
    action: "先确认 Organic 证明要求，再寄 3 款饮料级样品。", gap: "USDA Organic 进口证明待确认",
    contact: "sourcing@aurorabeverage.example", procurementUrl: "https://example.com/aurora/procurement", fit: 86,
    tags: ["食品级", "Organic", "500kg", "OEM", "饮料用"],
    evidence: [["08/20", "公开 RFQ", "采购有机抹茶粉 500kg，目标用于新品首批生产。", "FACT"], ["08/22", "买家官网", "新品系列新增 Matcha Energy 产品页。", "FACT"], ["08/24", "招聘页", "新增采购协调岗位，负责第二供应商开发。", "DERIVED"]],
    matches: [["产品形态", "饮料级抹茶粉", "饮料级抹茶粉", "PASS"], ["首批数量", "500 kg", "月产能 8,000 kg", "PASS"], ["OEM", "需要", "支持", "PASS"], ["Organic", "需要", "证书待核验", "UNKNOWN"]],
  },
  {
    id: "opp-002", rank: 2, decision: "PURSUE_NOW", decisionLabel: "立即追", decisionTone: "success", risk: "低风险",
    buyerName: "Kiyora Foods Co., Ltd.", country: "日本", city: "Osaka", industry: "食品配料",
    score: 87, truth: 82, window: "第二供应源", access: "可进入", accessTone: "success", published: "12 天前",
    demand: "烘焙级抹茶粉", quantity: "季度采购",
    whyNow: "近 30 天采购频率提升；现有进口记录显示正在增加第二供应来源。",
    whyNowReasons: ["近 30 天进口频率提升", "供应商登记入口开放", "第二供应源窗口明确"],
    action: "以第二供应源切入，先发送规格表和稳定供货证明。", gap: "无硬阻断；日文标签样稿可与报价并行准备",
    contact: "procurement@kiyora.example", procurementUrl: "https://example.com/kiyora/suppliers", fit: 91,
    tags: ["烘焙级", "季度采购", "日本", "稳定供货"],
    evidence: [["08/06", "贸易记录", "抹茶相关进口频次较上月增加。", "FACT"], ["08/18", "供应商页", "开放食品配料供应商登记。", "FACT"], ["08/21", "规则计算", "周期性采购窗口预计在 14 天内。", "DERIVED"]],
    matches: [["产品形态", "烘焙级", "烘焙级", "PASS"], ["供货周期", "季度稳定", "可满足", "PASS"], ["JAS", "未明确", "UNKNOWN", "UNKNOWN"], ["日文标签", "需要", "并行准备", "PASS"]],
  },
  {
    id: "opp-003", rank: 3, decision: "VERIFY_FIRST", decisionLabel: "补证后追", decisionTone: "warning", risk: "中风险",
    buyerName: "Northline Organic Retail GmbH", country: "德国", city: "Berlin", industry: "有机零售",
    score: 81, truth: 79, window: "需求明确", access: "待核验", accessTone: "danger", published: "18 天前",
    demand: "欧盟有机抹茶粉", quantity: "未披露",
    whyNow: "新建抹茶品类页并公开征集供应商；需求强，但农残标准与有机文件未完全披露。",
    whyNowReasons: ["新增抹茶品类页", "公开征集茶粉供应商", "疑似进入新品备货期"],
    action: "先索取完整规格和农残清单，再决定是否寄样。", gap: "EU Organic e-COI 与农残面板待确认",
    contact: "supplier@northline.example", procurementUrl: "https://example.com/northline/vendor", fit: 72,
    tags: ["EU Organic", "零售包装", "农残要求", "数量未知"],
    evidence: [["08/10", "买家官网", "新增 Organic Matcha 分类页。", "FACT"], ["08/11", "供应商入口", "公开征集茶粉供应商。", "FACT"], ["08/12", "AI 判断", "可能处于新品备货期。", "INFERENCE"]],
    matches: [["产品形态", "零售级抹茶", "支持", "PASS"], ["EU Organic", "需要", "待核验", "UNKNOWN"], ["农残面板", "未披露", "可检测", "UNKNOWN"], ["零售包装", "需要", "支持 OEM", "PASS"]],
  },
  {
    id: "opp-004", rank: 4, decision: "PURSUE_NOW", decisionLabel: "立即追", decisionTone: "success", risk: "低风险",
    buyerName: "Verdant Ingredients Ltd.", country: "英国", city: "London", industry: "食品原料分销",
    score: 78, truth: 76, window: "询价新增", access: "可进入", accessTone: "success", published: "21 天前",
    demand: "餐饮渠道抹茶", quantity: "1,000 kg / 年",
    whyNow: "供应商目录新增亚洲茶粉类别，并出现年度框架询价。",
    whyNowReasons: ["年度框架询价已出现", "新增亚洲茶粉目录", "数量与采购周期明确"],
    action: "提交年度阶梯报价与欧洲仓交期方案。", gap: "欧洲仓交期需要进一步确认",
    contact: "ingredients@verdant.example", procurementUrl: "https://example.com/verdant/tenders", fit: 80,
    tags: ["餐饮渠道", "年度框架", "1,000kg", "阶梯报价"],
    evidence: [["08/07", "公开询价", "年度茶粉原料供应商征集。", "FACT"]],
    matches: [["年需求", "1,000 kg", "可满足", "PASS"], ["交期", "欧洲仓", "可报价后确认", "PASS"]],
  },
  {
    id: "opp-005", rank: 5, decision: "WATCH", decisionLabel: "继续观察", decisionTone: "neutral", risk: "中风险",
    buyerName: "Solace Wellness Foods Pty Ltd", country: "澳大利亚", city: "Sydney", industry: "健康食品",
    score: 74, truth: 73, window: "新品验证", access: "补充条件", accessTone: "warning", published: "28 天前",
    demand: "高色泽抹茶粉", quantity: "样品后确认",
    whyNow: "公开测试抹茶蛋白粉新品，正在收集小样与稳定性色泽数据。",
    whyNowReasons: ["新品进入消费者测试", "正在收集小样", "商业采购量尚未形成"],
    action: "继续监控商业量与目标价；出现明确采购量后再发送 COA。", gap: "数量与目标价格未披露",
    contact: "innovation@solace.example", procurementUrl: "https://example.com/solace/contact", fit: 77,
    tags: ["高色泽", "蛋白粉", "先寄样", "数量未知"],
    evidence: [["07/31", "新品页", "抹茶蛋白粉进入消费者测试。", "FACT"]],
    matches: [["色泽", "高色泽", "可提供色差数据", "PASS"], ["数量", "未披露", "UNKNOWN", "UNKNOWN"]],
  },
];

export const countrySignals = [["美国", 12, 82], ["欧盟", 9, 68], ["日本", 7, 55], ["英国", 4, 34], ["其他", 4, 28]];
